### ISSUE TITLE
Baruwa and postfix

### ISSUE THREAD

**Issue by gsnick** [akissa/baruwa#76]
Hello,

Can Baruwa work with postfix? 
If yes could someone help understand why in the attached screenshot Baruwa sees 0 MTA processes?
Thank you in advance!
![baruwa](https://cloud.githubusercontent.com/assets/13554250/8955973/2954445e-35fa-11e5-91f8-ea01aa6b08d5.png)

**Comment by syska** [comment]
No, I think it's Exim only ... 

But since Baruwa is a full system I don't see why you would want to change it to Postfix. This just means that Baruwa should support even more MTA's and I think that is a waste of time. But i'm sure @akissa will accept pull request if you create Postfix support.

**Comment by fluxlabs** [comment]
Baruwa does support postfix, but you'll have to write the config a for it.

Baruwa v1 was postfix, v2 moved to exim. Baruwa enterprise is a complete OS install.

--
Jeremy McSpadden | Flux Labs
Local - 850-250-5590x501<tel:850-250-5590;501> | Mobile - 850-890-2543<tel:850-890-2543>
Fax - 850-254-2955<tel:850-254-2955> | Toll Free - 877-699-FLUX<tel:877-699-FLUX>
Web - http://www.fluxlabs.net<http://www.fluxlabs.net/>


On Jul 29, 2015, at 6:00 AM, gsnick <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

Can Baruwa work with postfix?
If yes could someone help understand why in the attached screenshot Baruwa sees 0 MTA processes?
Thank you in advance!
[baruwa]<https://cloud.githubusercontent.com/assets/13554250/8955973/2954445e-35fa-11e5-91f8-ea01aa6b08d5.png>

-

**Comment by akissa** [comment]
Pull requests more than welcome.

**Comment by topstarnetwork** [comment]
Are you going to deliver baruwa 2.0 with postfix support?
If not please advise.

**Comment by akissa** [comment]
No, i have no interest in postfix but if someone whats to contribute postfix support we will merge it.
